const {
  IOSConfig,
  withAppDelegate,
  withDangerousMod,
  withInfoPlist,
  withXcodeProject,
} = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

// iOS 27 refuses to launch an app built against its SDK unless the app adopts
// the UIScene life cycle: UIKit hits a `brk` in
// `_UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption` while
// creating the first scene, before any of our code runs. That was the App
// Review rejection of 1.19.0 (crash on launch, iPad Air M3, iPadOS 27.0).
//
// Expo SDK 54's AppDelegate template is still app-delegate based (it creates
// the UIWindow in didFinishLaunching). Expo 57 ships `ExpoAppSceneDelegate`
// for this; this plugin backports it until we're on an SDK that generates it:
//   1. Info.plist declares a single-scene manifest pointing at SceneDelegate.
//   2. SceneDelegate.swift creates the window from the connecting scene and
//      starts React Native into it, rebuilding the launch options so
//      Linking.getInitialURL() still sees a URL that cold-started the app
//      (a .torrent opened from Files arrives in the scene's connection
//      options now, not in the app delegate's launch options).
//   3. AppDelegate stops creating the window in release builds.
// Under scenes UIKit stops calling the app delegate's URL, user-activity and
// foreground/background methods, so SceneDelegate re-feeds them to it; that
// keeps our Linking overrides and every Expo subscriber working unchanged.
//
// Debug builds keep starting React Native in didFinishLaunching:
// expo-dev-launcher (debug-only) fatalErrors there if the app delegate has no
// window yet. SceneDelegate adopts that window into the scene instead of
// creating one. Drop this plugin once the Expo SDK template adopts scenes.

const SCENE_DELEGATE_FILE = "SceneDelegate.swift";

const SCENE_DELEGATE_SOURCE = `// Generated by plugins/withSceneLifecycle.js. Do not edit; edit the plugin.
// Backport of Expo SDK 57's ExpoAppSceneDelegate: iOS 27 won't launch an app
// that hasn't adopted the UIScene life cycle.

import Expo
import React

class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  private var appDelegate: AppDelegate? {
    UIApplication.shared.delegate as? AppDelegate
  }

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene, let appDelegate else {
      return
    }

    if let window = appDelegate.window {
      // Debug builds already started React Native in didFinishLaunching.
      window.windowScene = windowScene
      window.makeKeyAndVisible()
      self.window = window
    } else {
      guard let factory = appDelegate.reactNativeFactory else {
        fatalError("SceneDelegate: AppDelegate has no React Native factory")
      }
      let window = UIWindow(windowScene: windowScene)
      self.window = window
      // Code that reads UIApplication.shared.delegate?.window (expo-system-ui,
      // reanimated's keyboard observer) keeps working.
      appDelegate.window = window

      let browsingWebActivity = connectionOptions.userActivities.first {
        $0.activityType == NSUserActivityTypeBrowsingWeb
      }
      factory.startReactNative(
        withModuleName: "main",
        in: window,
        launchOptions: Self.launchOptions(
          url: connectionOptions.urlContexts.first?.url,
          userActivity: browsingWebActivity
        )
      )
    }

    // The app delegate used to get these right after launching too.
    connectionOptions.urlContexts.forEach { open($0) }
    connectionOptions.userActivities.forEach { continueActivity($0) }
    if let shortcutItem = connectionOptions.shortcutItem {
      appDelegate.application(UIApplication.shared, performActionFor: shortcutItem) { _ in }
    }
  }

  func sceneDidDisconnect(_ scene: UIScene) {
    window = nil
  }

  func sceneDidBecomeActive(_ scene: UIScene) {
    appDelegate?.applicationDidBecomeActive(UIApplication.shared)
  }

  func sceneWillResignActive(_ scene: UIScene) {
    appDelegate?.applicationWillResignActive(UIApplication.shared)
  }

  func sceneWillEnterForeground(_ scene: UIScene) {
    appDelegate?.applicationWillEnterForeground(UIApplication.shared)
  }

  func sceneDidEnterBackground(_ scene: UIScene) {
    appDelegate?.applicationDidEnterBackground(UIApplication.shared)
  }

  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    URLContexts.forEach { open($0) }
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    continueActivity(userActivity)
  }

  func windowScene(
    _ windowScene: UIWindowScene,
    performActionFor shortcutItem: UIApplicationShortcutItem,
    completionHandler: @escaping (Bool) -> Void
  ) {
    guard let appDelegate else {
      completionHandler(false)
      return
    }
    appDelegate.application(
      UIApplication.shared,
      performActionFor: shortcutItem,
      completionHandler: completionHandler
    )
  }

  private func open(_ context: UIOpenURLContext) {
    var options: [UIApplication.OpenURLOptionsKey: Any] = [
      .openInPlace: context.options.openInPlace
    ]
    if let sourceApplication = context.options.sourceApplication {
      options[.sourceApplication] = sourceApplication
    }
    if let annotation = context.options.annotation {
      options[.annotation] = annotation
    }
    _ = appDelegate?.application(UIApplication.shared, open: context.url, options: options)
  }

  private func continueActivity(_ userActivity: NSUserActivity) {
    _ = appDelegate?.application(
      UIApplication.shared,
      continue: userActivity,
      restorationHandler: { _ in }
    )
  }

  // RCTLinkingManager's getInitialURL only reads the launch options, by these
  // exact keys. Built from the raw strings because the UIApplication accessors
  // are deprecated in favor of the scene APIs.
  private static func launchOptions(
    url: URL?,
    userActivity: NSUserActivity?
  ) -> [UIApplication.LaunchOptionsKey: Any]? {
    var launchOptions: [UIApplication.LaunchOptionsKey: Any] = [:]
    if let url {
      launchOptions[UIApplication.LaunchOptionsKey(rawValue: "UIApplicationLaunchOptionsURLKey")] = url
    }
    if let userActivity {
      launchOptions[UIApplication.LaunchOptionsKey(rawValue: "UIApplicationLaunchOptionsUserActivityDictionaryKey")] = [
        "UIApplicationLaunchOptionsUserActivityTypeKey": userActivity.activityType,
        "UIApplicationLaunchOptionsUserActivityKey": userActivity,
      ]
    }
    return launchOptions.isEmpty ? nil : launchOptions
  }
}
`;

// The SDK 54 template's window setup, replaced verbatim. Throwing when it's
// missing beats silently shipping an AppDelegate that starts React Native
// twice (or never).
const WINDOW_BLOCK = `#if os(iOS) || os(tvOS)
    window = UIWindow(frame: UIScreen.main.bounds)
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions)
#endif`;

const WINDOW_BLOCK_PATCHED = `    // Release builds create the window and start React Native in SceneDelegate
    // (iOS 27 requires the scene life cycle). Debug builds still start here
    // because expo-dev-launcher needs the window during didFinishLaunching;
    // SceneDelegate adopts it into the scene.
#if DEBUG
    window = UIWindow(frame: UIScreen.main.bounds)
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions)
#endif`;

function withSceneManifest(config) {
  return withInfoPlist(config, (config) => {
    config.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: "Default Configuration",
            UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate",
          },
        ],
      },
    };
    return config;
  });
}

function withSceneAppDelegate(config) {
  return withAppDelegate(config, (config) => {
    const { contents, language } = config.modResults;
    if (language !== "swift") {
      throw new Error(`withSceneLifecycle: expected a Swift AppDelegate, got ${language}`);
    }
    if (contents.includes(WINDOW_BLOCK_PATCHED)) return config;
    if (!contents.includes(WINDOW_BLOCK)) {
      throw new Error(
        "withSceneLifecycle: AppDelegate.swift no longer matches the SDK 54 template's window setup; " +
          "update the plugin (or drop it if the new template already adopts scenes)",
      );
    }
    config.modResults.contents = contents.replace(WINDOW_BLOCK, WINDOW_BLOCK_PATCHED);
    return config;
  });
}

function withSceneDelegateFile(config) {
  config = withDangerousMod(config, [
    "ios",
    (config) => {
      const projectName = IOSConfig.XcodeUtils.getProjectName(config.modRequest.projectRoot);
      const filePath = path.join(config.modRequest.platformProjectRoot, projectName, SCENE_DELEGATE_FILE);
      fs.writeFileSync(filePath, SCENE_DELEGATE_SOURCE);
      return config;
    },
  ]);

  return withXcodeProject(config, (config) => {
    const projectName = IOSConfig.XcodeUtils.getProjectName(config.modRequest.projectRoot);
    const filepath = `${projectName}/${SCENE_DELEGATE_FILE}`;
    if (!config.modResults.hasFile(filepath)) {
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath,
        groupName: projectName,
        project: config.modResults,
      });
    }
    return config;
  });
}

function withSceneLifecycle(config) {
  config = withSceneManifest(config);
  config = withSceneAppDelegate(config);
  return withSceneDelegateFile(config);
}

module.exports = withSceneLifecycle;
