import {
  Activity,
  Anchor,
  Atom,
  Award,
  BarChart3,
  Bell,
  Bot,
  Briefcase,
  Camera,
  CalendarDays,
  Captions,
  Cast,
  Clapperboard,
  Cloud,
  Coffee,
  Cpu,
  Disc,
  Download,
  Drama,
  Film,
  Flag,
  Flame,
  Folder,
  Gamepad2,
  Gauge,
  Gem,
  Globe,
  Hammer,
  HardDrive,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Image as ImageIcon,
  Inbox,
  Joystick,
  LayoutDashboard,
  Library,
  Lightbulb,
  Map,
  Monitor,
  Music,
  Newspaper,
  Package,
  PlayCircle,
  Power,
  Radar,
  Radio,
  Rocket,
  Server,
  Shield,
  Sparkles,
  Star,
  Sun,
  Tent,
  Tv,
  Users,
  Wifi,
  Zap,
  type LucideIcon,
} from "lucide-react-native";

// Curated lucide registry for dashboard icons. Imports are named — tree-shaking
// keeps the bundle lean instead of pulling the whole namespace. Order chosen so
// the most likely picks for a media/server dashboard appear first.
export const LUCIDE_BY_NAME = {
  LayoutDashboard,
  Home,
  Server,
  HardDrive,
  Monitor,
  Cpu,
  Cloud,
  Wifi,
  Film,
  Tv,
  Clapperboard,
  PlayCircle,
  Music,
  Headphones,
  Disc,
  Radio,
  Library,
  Newspaper,
  ImageIcon,
  Camera,
  Cast,
  Download,
  Inbox,
  Folder,
  Package,
  Gauge,
  BarChart3,
  Activity,
  HeartPulse,
  Radar,
  Power,
  Zap,
  Shield,
  Bell,
  Bot,
  Captions,
  Star,
  Heart,
  Flame,
  Sparkles,
  Sun,
  Gem,
  Rocket,
  Globe,
  Map,
  Tent,
  Anchor,
  Atom,
  Award,
  Briefcase,
  Coffee,
  Drama,
  Flag,
  Gamepad2,
  Hammer,
  Joystick,
  Lightbulb,
  Users,
} as const satisfies Record<string, LucideIcon>;

export type DashboardIconName = keyof typeof LUCIDE_BY_NAME;

export const LUCIDE_ICON_NAMES = Object.keys(
  LUCIDE_BY_NAME,
) as readonly DashboardIconName[];

export const DEFAULT_DASHBOARD_ICON: DashboardIconName = "LayoutDashboard";

export function resolveDashboardIcon(name: string | undefined): LucideIcon {
  if (name && name in LUCIDE_BY_NAME) {
    return LUCIDE_BY_NAME[name as DashboardIconName];
  }
  return LUCIDE_BY_NAME[DEFAULT_DASHBOARD_ICON];
}
