import {
  Activity,
  Anchor,
  Atom,
  Award,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Briefcase,
  Camera,
  CalendarDays,
  Captions,
  Cast,
  Clapperboard,
  Cloud,
  Coffee,
  Container,
  Cpu,
  Database,
  ExternalLink,
  Disc,
  Download,
  Drama,
  Film,
  Flag,
  Flame,
  Folder,
  Gamepad2,
  Gauge,
  Gem,
  Globe,
  Hammer,
  HardDrive,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Image as ImageIcon,
  Inbox,
  Joystick,
  KeyRound,
  LayoutDashboard,
  LayoutGrid,
  Library,
  Lightbulb,
  Link,
  Lock,
  Map,
  Monitor,
  MonitorPlay,
  Music,
  Network,
  Newspaper,
  Package,
  PlayCircle,
  Power,
  Radar,
  Radio,
  Rocket,
  Router,
  Server,
  Settings,
  Shield,
  Sparkles,
  Star,
  Sun,
  Tent,
  Terminal,
  Tv,
  Users,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react-native";

// Curated lucide registry for dashboard icons. Imports are named — tree-shaking
// keeps the bundle lean instead of pulling the whole namespace. Order chosen so
// the most likely picks for a media/server dashboard appear first.
export const LUCIDE_BY_NAME = {
  LayoutDashboard,
  LayoutGrid,
  Home,
  Server,
  HardDrive,
  Monitor,
  MonitorPlay,
  Cpu,
  Cloud,
  Wifi,
  Film,
  Tv,
  Clapperboard,
  PlayCircle,
  Music,
  Headphones,
  Disc,
  Radio,
  Library,
  BookOpen,
  Newspaper,
  ImageIcon,
  Camera,
  Cast,
  Download,
  Inbox,
  CalendarDays,
  Folder,
  Package,
  Gauge,
  BarChart3,
  Activity,
  HeartPulse,
  Radar,
  Power,
  Zap,
  Shield,
  Bell,
  Bot,
  Captions,
  Star,
  Heart,
  Flame,
  Sparkles,
  Sun,
  Gem,
  Rocket,
  Globe,
  Map,
  Tent,
  Anchor,
  Atom,
  Award,
  Briefcase,
  Coffee,
  Drama,
  Flag,
  Gamepad2,
  Hammer,
  Joystick,
  Lightbulb,
  Users,
  // Web-shortcut flavored additions (#344): self-hosted admin UIs, routers,
  // containers and the like. Appended so existing dashboard picks keep their
  // position in the picker grid.
  Link,
  ExternalLink,
  Router,
  Network,
  Container,
  Database,
  Terminal,
  Settings,
  Wrench,
  KeyRound,
  Lock,
} as const satisfies Record<string, LucideIcon>;

export type DashboardIconName = keyof typeof LUCIDE_BY_NAME;

export const LUCIDE_ICON_NAMES = Object.keys(
  LUCIDE_BY_NAME,
) as readonly DashboardIconName[];

import { DEFAULT_DASHBOARD_ICON as PURE_DEFAULT_DASHBOARD_ICON } from "@/lib/dashboard-defaults";

export const DEFAULT_DASHBOARD_ICON = PURE_DEFAULT_DASHBOARD_ICON satisfies DashboardIconName;

export function resolveDashboardIcon(name: string | undefined): LucideIcon {
  if (name && name in LUCIDE_BY_NAME) {
    return LUCIDE_BY_NAME[name as DashboardIconName];
  }
  return LUCIDE_BY_NAME[DEFAULT_DASHBOARD_ICON];
}

// Web shortcuts (#344) share the registry so the same picker sheet serves both.
export const DEFAULT_SHORTCUT_ICON = "Globe" satisfies DashboardIconName;

export function resolveShortcutIcon(name: string | undefined): LucideIcon {
  if (name && name in LUCIDE_BY_NAME) {
    return LUCIDE_BY_NAME[name as DashboardIconName];
  }
  return LUCIDE_BY_NAME[DEFAULT_SHORTCUT_ICON];
}
